/**
 * Creates an object with keys generated by running the provided function for each key and the same values as the provided object.
 *
 * @param {{}} obj
 * @param {Function} fn
 */
const mapKeys = (obj: {}, fn: Function) =>
  Object.keys(obj).reduce((acc, k) => {
    (acc as any)[fn((obj as any)[k], k, obj)] = (obj as any)[k];
    return acc;
  }, {});

export default mapKeys;
