/**
 * Creates an object with the same keys as the provided object and values generated by running the provided function for each value.
 *
 * @param {{}} obj
 * @param {Function} fn
 */
const mapValues = (obj: {}, fn: Function) =>
  Object.keys(obj).reduce((acc, k) => {
    (acc as any)[k] = fn((obj as any)[k], k, obj);
    return acc;
  }, {});
export default mapValues;
